apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: banana-beta-hpa
  namespace: banana-beta
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: banana-beta
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
