apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: hello-backend
  namespace: hello-backend
spec:
  replicas: 2
  # Pod가 'Ready' 상태가 된 후, 최소 10초가 지나야 'Available'로 간주합니다.
  minReadySeconds: 10
  selector:
    matchLabels:
      app: hello-backend
  template:
    metadata:
      labels:
        app: hello-backend
    spec:
      revisionHistoryLimit: 3
      # Pod 종료 신호(SIGTERM)를 받고,  ALB에서 완전히 제외될 때까지 60초간 대기합니다.
      terminationGracePeriodSeconds: 60
      serviceAccountName: secret-db-iam
      containers:
        - name: hello-backend
          image: 624577703989.dkr.ecr.ap-northeast-1.amazonaws.com/hackathon:20251107155602
          ports:
            - containerPort: 5000
          # Readiness Probe: Pod가 트래픽을 받을 준비가 되었는지 검사
          # 이 검사가 성공해야만 Kubernetes가 'Ready'로 인정하고,
          # ALB가 'Healthy'로 인정하여 트래픽을 보내기 시작합니다.
          readinessProbe:
            httpGet:
              path: / # Flask 앱의 '/' 경로
              port: 5000 # Flask 앱 포트
            initialDelaySeconds: 5 # Pod 시작 후 5초 뒤 검사 시작
            periodSeconds: 10 # 10초마다 검사
            timeoutSeconds: 2 # 2초 내 응답해야 함
            failureThreshold: 3 # 3번 실패 시 'NotReady'
          # Liveness Probe: Pod가 살아있는지(hang 걸리지 않았는지) 검사
          # 실패 시 Pod를 자동으로 재시작합니다.
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15 # Readiness보다 늦게 시작
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
  strategy:
    canary:
      stableService: hello-backend-stable
      canaryService: hello-backend-canary
      trafficRouting:
        alb:
          ingress: hello-backend-ingress
          servicePort: 80
      steps:
        # --- ✨ 이 두 단계를 추가합니다 ---
        - setCanaryScale:
            replicas: 2 # 1. 'replicas: 2'에 맞게 새 버전 Pod 2개를 즉시 띄웁니다.
        - pause: { duration: "3m" } # 2. 트래픽 0% 상태로 무기한 일시정지 하고 싶으면 { }
        # -------------------------------
        - setWeight: 25
        - pause: { duration: "2m" }
        - setWeight: 50
        - pause: { duration: "5m" }
        - setWeight: 75
        - pause: { duration: "1m" }
