apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: banana-ingress
  namespace: banana
spec:
  rules:
    - host: beta.gyungdal.cc
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: banana-ingress-preview
  namespace: banana
spec:
  rules:
    - host: rollouts-test-preview.beta.gyungdal.cc
